### ISSUE TITLE
Design the Write page for mobile use using responsive web

### ISSUE THREAD

**Issue by raipen** [SNS-md/front.md#14]
# 할 일
* 모바일로 우리 서비스에 글을 작성할때 작성란과 미리보기가 세로 분할되어 있어, 너무 폭이 좁아 보기 불편함
![image](https://user-images.githubusercontent.com/87058411/232469016-8bfc78f4-9a67-4bde-8ed7-d1bf4064ff29.png)
* 이를 모바일에서는 작성란과 미리보기란을 동시에 보여주는 것이 아니라 아래처럼 하나씩 선택해서 볼 수 있는 형태로 하려고함
![image](https://user-images.githubusercontent.com/87058411/232469302-acb329f0-6b71-45d6-816a-f7184fa59b3e.png)
* 미디어쿼리를 사용한 반응형 웹으로 제작하여, 화면이 넓은 경우(600px 이상)엔 지금처럼, 좁은 경우엔 선택형으로 변경

# 관련 학습
https://swm.elice.io/courses/67030/lectures/566683

**Comment by SeHyun-Kim04** [comment]
저번 디자인을 통해서 Bootstrap을 추가해두었습니다.
Bootstrap의 card 기능을 이용해서 구현하면 될 것 같습니다.

참고 URL : https://getbootstrap.com/docs/5.3/components/card/#navigation
